export const CHANGE_ACLPAGELOADING= 'CHANGE_ACLPAGELOADING';
export const FETCH_ROLES = 'FETCH_ROLES';
export const FETCH_PERMISSIONS = 'FETCH_PERMISSIONS';
export const FETCH_ROLE = 'FETCH_ROLE';
export const FETCH_USERS = 'FETCH_USERS';
