export const SETTING_REQUESTING = 'SETTING_REQUESTING';
export const SETTING_SUCCESS = 'SETTING_SUCCESS';
export const SETTING_FAILURE = 'SETTING_FAILURE';
export const SETTING_CHANGE_CATEGORY_EXPANDED = 'SETTING_CHANGE_CATEGORY_EXPANDED';

export const LAST_BLOG_POSTS_REQUESTING = 'LAST_BLOG_POSTS_REQUESTING';
export const LAST_BLOG_POSTS_SUCCESS = 'LAST_BLOG_POSTS_SUCCESS';
export const LAST_BLOG_POSTS_FAILURE = 'LAST_BLOG_POSTS_FAILURE';

export const SLIDER_REQUESTING = 'SLIDER_REQUESTING';
export const SLIDER_SUCCESS = 'SLIDER_SUCCESS';
export const SLIDER_FAILURE = 'SLIDER_POSTS_FAILURE';

export const PAYLOAD_PRODUCTS_REQUESTING = 'PAYLOAD_PRODUCTS_REQUESTING';
export const PAYLOAD_PRODUCTS_SUCCESS = 'PAYLOAD_PRODUCTS_SUCCESS';
export const PAYLOAD_PRODUCTS_FAILURE = 'PAYLOAD_PRODUCTS_POSTS_FAILURE';

export const SHOP_REQUESTING = 'SHOP_REQUESTING';
export const SHOP_SUCCESS = 'SHOP_SUCCESS';
export const SHOP_FAILURE = 'SHOP_POSTS_FAILURE';
