<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Product extends Model
{

    use SoftDeletes;

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::created(function ($model) {

            \Artisan::call('cache:clear');
        });

        static::updated(function ($model) {
            \Artisan::call('cache:clear');
        });

        static::deleted(function ($model) {
            \Artisan::call('cache:clear');
        });

    }

}
