<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Product extends Model
{

    protected $table = 'products';

    protected $guarded = [];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::created(function ($model) {

            \Artisan::call('cache:clear');
        });

        static::updated(function ($model) {
            \Artisan::call('cache:clear');
        });

        static::deleted(function ($model) {
            \Artisan::call('cache:clear');
        });

    }

    public function attributes()
    {
        return $this->belongsToMany(GroupAttribute::class, 'group_attribute_product', 'product_id', 'attribute_id')->withPivot('value', 'order', 'main');
    }

    public function categories()
    {
        return $this->belongsToMany(ProductCategory::class, 'product_categories', 'product_id', 'category_id');
    }


    public function brand()
    {
        return $this->belongsTo(Brand::class);
    }

}
