<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Domain extends Model
{
    protected $primaryKey = 'key';

    protected $table = 'domain';

    public $incrementing = false;

    protected $guarded = [];


    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::created(function ($model) {

            \Cache::forget('setting');
        });

        static::updated(function ($model) {
            \Cache::forget('setting');
        });

        static::deleted(function ($model) {
            \Cache::forget('setting');
        });

    }


    public function app()
    {
        return $this->belongsToMany(Links::class, 'domain_links')->where('type', '=', 'app')->withPivot(['value']);
    }

    public function license()
    {
        return $this->belongsToMany(Links::class, 'domain_links')->where('type', '=', 'license')->withPivot(['value']);
    }


    public function socialMedias()
    {
        return $this->belongsToMany(Links::class, 'domain_links')->where('type', '=', 'social')->withPivot(['value']);
    }


    public function communicationChannels()
    {
        return $this->belongsToMany(Links::class, 'domain_links')->where('type', '=','contact')->withPivot(['value']);
    }
}
