<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class File extends Model
{
    protected $table = 'file';

    protected $primaryKey = 'id';

    protected $guarded = [];


    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::created(function ($model) {
            if ($model->fileable_type == Gallery::class) {
                \Cache::forget('slider');
            }
        });

        static::updated(function ($model) {
            if ($model->fileable_type == Gallery::class) {
                \Cache::forget('slider');
            }
        });

        static::deleted(function ($model) {
            if ($model->fileable_type == Gallery::class) {
                \Cache::forget('slider');
            }
        });

    }



    // File Relation
    public function fileable()
    {
        return $this->morphTo();
    }
}
