<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Gallery extends Model
{
    protected $table = 'gallery';

    protected $primaryKey = 'id';

    protected $guarded = [];


    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::created(function ($model) {

            \Cache::forget('slider');
        });

        static::updated(function ($model) {
            \Cache::forget('slider');
        });

        static::deleted(function ($model) {
            \Cache::forget('slider');
        });

    }


    public function files()
    {
        return $this->morphMany(File::class, 'fileable');
    }


    public function createdBy()
    {
        return $this->belongsTo(User::class, 'created_by');
    }

}
