<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Links extends Model
{
    protected $table = 'links';


    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::created(function ($model) {

            \Cache::forget('setting');
        });

        static::updated(function ($model) {
            \Cache::forget('setting');
        });

        static::deleted(function ($model) {
            \Cache::forget('setting');
        });

    }
}
