<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Tag extends Model
{
    protected $table = 'tag';

    protected $primaryKey = 'id';

    protected $guarded = [];

    public $timestamps= false;

    protected $hidden = ['pivot'];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::created(function ($model) {

            \Artisan::call('cache:clear');
        });

        static::updated(function ($model) {
            \Artisan::call('cache:clear');
        });

        static::deleted(function ($model) {
            \Artisan::call('cache:clear');
        });

    }


    public function contents()
    {
        return $this->belongsToMany(BlogContent::class, 'blog_tags', 'tag_id', 'content_id');
    }

}
